In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
# 設定 data_path, 並讀取 app_train
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

In [4]:
app_train.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [5]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)


WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [45]:
"""
Your Code Here(by Pandas)
"""
print("Before coding:\nThe shape of sub_train:")
print(sub_train.shape)
print("\nThe head of sub_train:")
print(sub_train.head())


le = LabelEncoder()
le.fit(sub_train['WEEKDAY_APPR_PROCESS_START'])
a = le.transform(sub_train['WEEKDAY_APPR_PROCESS_START'])

sub_train_enc = pd.get_dummies(a)

print("\nAfter coding:\nThe head of sub_train_enc:")
print(sub_train_enc.head())
print("\nThe shape of sub_train_enc:")
print(sub_train_enc.shape)

Before coding:
The shape of sub_train:
(307511, 1)

The head of sub_train:
  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

After coding:
The head of sub_train_enc:
   0  1  2  3  4  5  6
0  0  0  0  0  0  0  1
1  0  1  0  0  0  0  0
2  0  1  0  0  0  0  0
3  0  0  0  0  0  0  1
4  0  0  0  0  1  0  0

The shape of sub_train_enc:
(307511, 7)


In [16]:
sub_train['WEEKDAY_APPR_PROCESS_START']

0         WEDNESDAY
1            MONDAY
2            MONDAY
3         WEDNESDAY
4          THURSDAY
5         WEDNESDAY
6            SUNDAY
7            MONDAY
8         WEDNESDAY
9          THURSDAY
10         SATURDAY
11           FRIDAY
12           FRIDAY
13         THURSDAY
14           MONDAY
15         SATURDAY
16         THURSDAY
17           MONDAY
18           FRIDAY
19           MONDAY
20           FRIDAY
21           MONDAY
22         THURSDAY
23           FRIDAY
24         THURSDAY
25         SATURDAY
26           MONDAY
27         SATURDAY
28        WEDNESDAY
29          TUESDAY
            ...    
307481       FRIDAY
307482     THURSDAY
307483       MONDAY
307484       MONDAY
307485     SATURDAY
307486     SATURDAY
307487    WEDNESDAY
307488    WEDNESDAY
307489       FRIDAY
307490     SATURDAY
307491     SATURDAY
307492       FRIDAY
307493       MONDAY
307494       MONDAY
307495    WEDNESDAY
307496     THURSDAY
307497     THURSDAY
307498       MONDAY
307499      TUESDAY


In [26]:
"""
Your Code Here(By sklearn)
"""
from sklearn.preprocessing import LabelEncoder
print("-----------Start to Label Encoding for encoding string to integer----------------")
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(sub_train['WEEKDAY_APPR_PROCESS_START'])
print(integer_encoded)

print("-----------Start One Hot Encoding----------------")
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(sparse=False, categories='auto') 
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1) 
onehot_encoded = onehot_encoder.fit_transform(integer_encoded) 
print(onehot_encoded) 

-----------Start to Label Encoding for encoding string to integer----------------
[6 1 1 ... 4 6 4]
-----------Start One Hot Encoding----------------
[[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]]


In [47]:
print(onehot_encoded.shape)

(307511, 7)
